//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inserting_Data_using_Ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_questions
    {
        public int q_id { get; set; }
        public string q_name { get; set; }
        public string q_A { get; set; }
        public string q_B { get; set; }
        public string q_C { get; set; }
        public string q_D { get; set; }
        public string Correct_optn { get; set; }
    }
}
